# Generated by Django 6.0 on 2026-01-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], default='student', max_length=10, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.userprofile', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.userprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Связь учитель-ученик',
                'verbose_name_plural': 'Связи учитель-ученик',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
