# Generated by Django 6.0 on 2026-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_avatar_userprofile_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
